// simport type { Metadata } from "next";
// import  Link from "next/link";
// import localFont from "next/font/local";
import "./globals.css";
import Providers from "@/provider"
// import { Button } from "@/components/ui/button"
import Footer from "@/components/footer"
import Header from "@/components/header"


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <>
    <html lang="en">
      <body>
        <Providers>
        {/* <div className="flex min-h-screen flex-col"> */}
        <div className="min-h-screen flex flex-col bg-gradient-to-b from-gray-900 to-gray-800 text-white">
        {/* <div> */}
            <Header />
            {/* <main className="flex-1"> */}
            {/* <main className="flex flex-col min-h-full px-4 sm:px-20 py-6 sm:py-10 bg-privy-light-blue"> */}
            <main >
              {children}
            </main>
            <Footer />
          </div>
        </Providers>
      </body>
      </html>
      </>
  );
}
